### PR TITLE
Updated admin.py

### PR DESCRIPTION
**Pull request by epicserve**
- added the slug to the list_display
- added search_fields

### CODE REVIEW

**Comment by hcarvalhoalves** [comment]
Thank you for the pull request. Can you explain commit 30dd950f better? Under which circumstances does the backend raise `InternalError` instead of `IntegrityError`?

**Comment by epicserve** [comment]
It raises the error when you submit a tag in a different case for a tag that already exists in another case. Example if I've already tagged something with "Washington" and then I tag something else as "washington" the exception happens.

**Comment by hcarvalhoalves** [comment]
Ok, I see it. The problem is, the way `taggit` deals with casing (or anything that generates the same `slug`) is broken by default. I commented this on another pull request (https://github.com/hcarvalhoalves/django-taggit/pull/2#issuecomment-7442452).

> Now about the behavior with unicode characters... the correct approach here would be changing how taggit behaves, which is pretty stupid to begin with. Instead of catching IntegrityError and appending a number to the slug until it's unique, it should consider anything that normalizes to the same slug as the same Tag. I'll submit a patch for that myself since the default behavior is broken for my site too.

**Comment by epicserve** [comment]
I'm not a fan of how it handles casing either and have thought about either doing it the way you described or making a way that a manager could merge tags into a single case by picking the case that is preferred.

However, I made the fix because somehow the way it currently works is broken for me. I'm guessing it's because I'm running Django v1.4 and psycopg2 v2.4.5. So would there be any harm in merging in my pull request and then later changing the behavior of casing in a new branch?

**Comment by hcarvalhoalves** [comment]
> So would there be any harm in merging in my pull request and then later changing the behavior of casing in a new branch?

No, I don't think so. Although the "behavior" is broken, this is a bugfix anyway. Thank you very much.

**Comment by hcarvalhoalves** [comment]
@epicserve I've pushed a new branch with different behavior. It avoids as much as possible to insert a new tag if a previous one with the same slug already exists. Check it out: https://github.com/hcarvalhoalves/django-taggit/tree/ignore-unique-slugs

**Comment by epicserve** [comment]
So I'm taking a look at your new branch ... Why did you change the max_length on the model for both name and slug to 255. Why would anyone want a tag with that many characters?

**Comment by hcarvalhoalves** [comment]
@epicserve In my particular case, I was hitting the size limit (some movie names are longer than that). Also, arbitrary lengths don't make sense anyway: https://github.com/hcarvalhoalves/django-taggit/commit/6facf33e67228d73c3fda1ea3bf0cd06b33fa2b5#commitcomment-1695442

**Pull request merged**
